services:
  localstack:
    container_name: rvtech-matf-2025-project
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            
      - "127.0.0.1:4510-4559:4510-4559"  
    environment:
      - SERVICES=lambda,s3,logs,dynamodb,cloudwatch,apigateway,cloudformation,iam,events
      - DEBUG=${DEBUG:-0}
    volumes:
      - "~/tmp:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"