version: '3.8'

services:
  localstack:
    container_name: rvtech-matf-2025-project
    image: localstack/localstack-pro  
    ports:
      - "127.0.0.1:4566:4566"           
      - "127.0.0.1:4510-4559:4510-4559"  
    environment:
      - SERVICES=lambda,s3,logs,dynamodb,cloudwatch,apigateway,cloudformation,iam,events,sqs,sns
      - DEBUG=${DEBUG:-0}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    env_file:
      - .env  
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - charging-map-network

networks:
  charging-map-network:
    driver: bridge